service: taco-gallery

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  stage: dev
  environment:
    TESTNUM: 27
    TESTSTR: hello
    AUTH0_DOMAIN: pfernandom.auth0.com
    AUTH0_CLIENTID: L7YiTnpuzmfa1W9spj7fIpwXgHKzSmNX

resources:
  Resources:
    patients:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: name
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Patients

functions:
  authorizerFunc:
      handler: src/handlers/auth.auth
  helloPublic:
    handler: src/handlers/handler.init
    events:
      - http:
          path: init
          method: get
          cors: true
  graphqlUI:
    handler: src/handlers/lambda.handler
    events:
      - http:
          path: graphql
          method: get
          cors: true
  graphql:
    handler: src/handlers/lambda.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  graphqlsecure:
    handler: src/handlers/lambda.handler
    events:
      - http:
          path: graphqlsecure
          method: post
          cors: true
          authorizer: authorizerFunc


plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  dynamodb:
      start:
        migrate: true
  serverless-offline:
    port: 3333
    babelOptions:
      presets: ["es2015", "stage-2"]
